# Site settings
title: "Joel Tengco"
description: "My resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Joel Tengco"
resume_title:                   "Entry-Level Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jitengco@cpp.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "310-977-7425"
resume_contact_address:         "750 E 3rd St. Apt. K12, Pomona, CA 91766"

resume_header_contact_info:     "750 E 3rd St. Apt. K12, Pomona, CA 91766 • 310-977-7425 • jitengco@cpp.edu"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a recent graduate in Computer Science from Cal Poly Pomona.
  I am a person that genuinely enjoys learning new concepts and technologies.
  I am a person that starts on projects and tasks early to give enough time for thorough testing and analysis.
  I am always looking for opportunities to grow as a software engineer.
  One particular goal I have is to contribute towards software pertaining to education.
  Other topics that interest me are back-end development, machine learning and computer vision.
  I am truly a hard worker and when given enough time to learn and adapt, I can become very efficient in the work I do.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
resume_section_skills:          true
resume_section_projects:        true
resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/clovenski"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  # resume_linkedin_url:          ""
  # resume_instagram_url:         ""
  # resume_website_url:           ""
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
